# Generated by Django 4.1.7 on 2023-06-10 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=' ', srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=2, srid=4326),
            preserve_default=False,
        ),
    ]
