# Generated by Django 4.1.7 on 2023-06-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_amenity_location_house_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
